services:
  finlit:
    build: .
    container_name: finlit-chatbot
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.chroma:/app/.chroma
      - ./data:/app/data

  finlit-telegram:
    build: .
    container_name: finlit-telegram-bot
    command: ["finlit-telegram"]
    env_file:
      - .env
    volumes:
      - ./.chroma:/app/.chroma
      - ./data:/app/data
